name: ci-frontend-mobile-flow
# env:
#   PAT_TOKEN: ${{ secrets.PERSONAL2 }} # ${{ secrets.GITHUB_TOKEN }}

on: 
  repository_dispatch:
    types: [run-flutter-tests]
    # inputs:
    #   tunnel-url: 
    #     type: string
    #     required: true
jobs:
  run_frontend_deploy:
    runs-on: macos-latest
    # permissions:
    #   contents: write  # permissions to post into the repo
    steps:
      - name: frontend-steps
        run: |
          echo 'running-frontend; using ...'
          echo '- repo: ${{github.repository}}'
          echo '- ref: ${{github.ref}}'

        shell: bash
      - name: check local wget
        # if: ${{ contains(github.event.pull_request.labels.*.name, 'mobile') && github.ref_name != 'main' }}
        run: |
          # wget -S -O - ${{ github.event.client_payload.tunnel-url }}/api/docs   
          wget -S -O - ${{ github.event.client_payload.tunnel-url }}/index.html

      # - - - - - - - - - - - - - - - - - - - - - - - - -
      # process building & e2e for mobile
      # - - - - - - - - - - - - - - - - - - - - - - - - -
      - uses: actions/checkout@v4
        with:
          path: garden

      - name: flutter-app-e2e-emulator call
        uses: ./garden/.github/actions/flutter-app-e2e-emulator # ./.github/actions/flutter-app-deploy
        with: 
          strongline-api-tunneling-url: ${{inputs.strongline-api-tunneling-url}}
          strongline-api-tunneling-url-envvar: "BASEURL"          
          app-repository: ${{github.repository}} # ${{inputs.app-repository}} # "ahurtado-cm/app1_flutter"
          app-repository-ref: ${{github.ref}} # ${{inputs.app-repository-ref}}
          working-directory: "app4" # ${{inputs.working-directory}} # "app1-flutter"
          # PERSONAL_CHECKOUT_TOKEN: ${{ inputs.PERSONAL_CHECKOUT_TOKEN }} # secrets.
          # PERSONAL_RELEASE_TOKEN: ${{ inputs.PERSONAL_RELEASE_TOKEN }} # secrets.
          # release-tag: ${{inputs.release-tag}} # "v0.0.1"
          # release-repository: ${{inputs.release-repository}}
        # secrets: 
          ONESIGNAL_APP_ID_STAGING: ${{secrets.ONESIGNAL_APP_ID_STAGING}}

      

      # - - - - - - - - - - - - - - - - - - - - - -
      # trigger the ngrok stop flow (with an event)
      # - - - - - - - - - - - - - - - - - - - - - -

      - name: ngrok-stop Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ${{ secrets.PERSONAL2 }} # ${{ secrets.PAT_TOKEN }} #
          event-type: ngrok-stop
          client-payload: '{"ngrok_process_id": "${{ github.event.client_payload.ngrok_process_id }}"}'
